name: main
on:
  push:
    branches:
    - master
env:
  AWS_DEFAULT_REGION: 'eu-west-2'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs: deploy-site
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --delete
      env:
      AWS_S3_BUCKET: steven-website-01
      SOURCE_DIR: cloudresume/frontend
